require('dotenv').config({ path: 'backend/.env' });
const mongoose = require('mongoose');
const { Product } = require('../models');
const connectDB = require('../config/database');

const bags = [
    {
        name: "Zouk Women's Multicolor Tote",
        description: "Multicolor tote bag with roomy and casual design. Fits daily essentials, bottles, wallet, and phone.",
        price: 809,
        discount: 0,
        category: "6976f046204b7ebcf31f3629",
        images: [{ url: "https://images.openai.com/thumbnails/url/NYfVt3icDcnbDoIgAADQLyJb6gy31ro4Y5VWdpm9MEEHVAomUvpR_U9_U-f1fD9ca9X4llVU9NkpXeRAk2o4YI3OtKADKkur4VIpUbFpPfmfP4tyGNKEBAlx76ZH8AQDO-pQLAU36IxzvG8BKDYEX4LjSmK8RCfuvPmhi_VtZOPUoPYlEwVv63gXyQLOqaBuyu6Ee_3i6ogteJiyAZzBhzZVLd2SZV6YdGOR_gBSOj85", isPrimary: true }],
        stock: 50,
        ratings: { average: 4.5, count: 120 },
        tags: ["zouk", "tote", "bag", "multicolor", "casual"]
    },
    {
        name: "ZOUK Women's Printed Oversized Shoulder Bag",
        description: "Fashion-forward printed oversized shoulder bag. Spacious and perfect for daily use and casual outings.",
        price: 819,
        discount: 0,
        category: "6976f046204b7ebcf31f3629",
        images: [{ url: "https://images.openai.com/thumbnails/url/bU4p9HicDcnbDoIgAADQLzLLssKtNTTGrHUb2u3FIRZSyiVorf6qz-lv6rye76d2TtvI98-S3V_anSvPlbLf4dZRJ1iHqda3tdJaSD41k_9FcFUBzLJ3RWUEmW6271v-WGZLpFI3PKaJgwWyNsNni-gwSswIzP-_pV-M87N4nVOG_BCQJy6fKjt02N4bzIFqGSeqN7aN0rRipoeQNzGO1UefSCepKR33eye6FHSdWUwKljNTEevem7OvAxyn4UvT1s", isPrimary: true }],
        stock: 40,
        ratings: { average: 4.8, count: 85 },
        tags: ["zouk", "printed", "shoulder bag", "oversized"]
    },
    {
        name: "ZOUK FloMotif Sling Bag",
        description: "Sleek and compact sling bag with motif print. Stylish choice for everyday errands and outings.",
        price: 810,
        discount: 0,
        category: "6976f046204b7ebcf31f3629",
        images: [{ url: "https://images.openai.com/thumbnails/url/3jtgwXicDcndEkJAGADQJ8pPmdBM09RgDVMRGXXTsMRWy9r9Cj1U79Pb1Lk9308NwMRClssG85FBWUwgb1SpEpABwRJuqSzqljHSVKtu-b_FeleYCB9quBSvLnDMJr2YvHf3AY7JBu1v74mdq7MzDadAxAME5qXPcq3eGrqtGK2V-Ck67qLU4sl1PvCMWp42pkqrUPHWUeH5Yezch8winXtKVCTWzuC_qqfSR2H8A1dHPpU", isPrimary: true }],
        stock: 60,
        ratings: { average: 4.7, count: 95 },
        tags: ["zouk", "sling", "bag", "motif", "compact"]
    },
    {
        name: "Zouk Women's Red Kalamkari Shoulder Tote",
        description: "Richly designed ethnic Kalamkari print red shoulder tote. A stylish statement piece for any outfit.",
        price: 1409,
        discount: 0,
        category: "6976f046204b7ebcf31f3629",
        images: [{ url: "https://images.openai.com/thumbnails/url/ZvUblHicDcndCoIwGADQJ_Kn_CmFCIUamJSJGnYjc5tzlTrzy8qH6n16mzq35_upAeTgahpryf0tgVEFytZQ-QAYBFFJ12hD3UkpWr7uV_9zvT11EEmsgD6pgrqwMrKr9DG3a7aHdKSxeYj1_riFzEGGswxf8-o4sMLCViSa2XM83-KyR3l6Cl6cTNijFpkUySncCrO5bKoJd160iE0k_PzBiD_O08S3BdF3RfgDM1Q-Pw", isPrimary: true }],
        stock: 30,
        ratings: { average: 4.7, count: 45 },
        tags: ["zouk", "kalamkari", "tote", "red", "ethnic"]
    },
    {
        name: "Lavie Ficus Small Satchel",
        description: "Classy and neat small structured satchel. Perfect for formal or casual professional use.",
        price: 1158,
        discount: 0,
        category: "6976f046204b7ebcf31f3629",
        images: [{ url: "https://images.openai.com/thumbnails/url/JbtLp3icDclJDoIwAADAFwmIsmhiDFYpRIqGEK1cCC2rCra0GuFVfsff6Fzn-6mlZGKpqkVH-4HJIp9I0ulKJWQmG6rQR6uK-sFY01Vrvvrf0gnzBaTRNLhcXybpPYNobQBpChB65rjZpOMhdHbvwnzPaMxwDw_81MJhb9VH--YyaoTVnfgxPHoJtcoAuCWBZyjuycxGFnd8TeXlpaSA7xwqh-X5z4x", isPrimary: true }],
        stock: 25,
        ratings: { average: 4.9, count: 156 },
        tags: ["lavie", "satchel", "bag", "formal", "compact"]
    },
    {
        name: "Lavie Sport Pioneer Laptop Backpack",
        description: "Sporty and functional laptop backpack. Durable construction, ideal for college or daily commute.",
        price: 889,
        discount: 0,
        category: "6976f046204b7ebcf31f3629",
        images: [{ url: "https://images.openai.com/thumbnails/url/IvbmynicDclJDoIwFADQEzFEUYbEGIgRBUQjVcSNoZQCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbCYbtps://images.unsplash.com/photo-1544816157-431999a80ea1?w=800&q=80", isPrimary: true }],
        stock: 100,
        ratings: { average: 4.4, count: 210 },
        tags: ["lavie", "backpack", "sporty", "laptop", "pioneer"]
    }
];

async function seed() {
    try {
        await connectDB();
        console.log('Connected to database');
        for (const bag of bags) {
            const exists = await Product.findOne({ name: bag.name });
            if (!exists) {
                await Product.create(bag);
                console.log(`Added: ${bag.name}`);
            } else {
                console.log(`Skipped (exists): ${bag.name}`);
            }
        }
        console.log('Successfully added bags to Fashion category');
        process.exit(0);
    } catch (error) {
        console.error('Error seeding bags:', error);
        process.exit(1);
    }
}

seed();
